//
// Copyright (c) 2021 Murilo Ijanc' <mbsd@m0x.ru>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

//! Calamp LMDirect message parser.

use nom::bits::{bits, streaming};
use nom::bytes;
use nom::error::{Error, ErrorKind};
use nom::number::complete::{be_i32, be_u16, be_u32, be_u8};
use nom::sequence::tuple;
use nom::IResult;

#[derive(Debug)]
pub struct MobileID<'a>(&'a [u8]);

impl<'a> MobileID<'a> {
    pub fn len(&self) -> usize {
        self.0.len()
    }

    pub fn parse(input: &'a [u8]) -> IResult<&[u8], Self> {
        let (i, a): (&[u8], u8) = be_u8::<_, (_, ErrorKind)>(input).unwrap();
        let (i, b): (&[u8], &[u8]) = bytes::streaming::take(a)(i)?;
        Ok((i, Self(b)))
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

impl<'a> ToString for MobileID<'a> {
    fn to_string(&self) -> String {
        let mut id = String::from("");
        for d in self.0.iter() {
            id.push_str(&format!("{0:2x}", d))
        }
        id
    }
}

pub fn parse_service_type(input: &[u8]) -> IResult<&[u8], u8> {
    let (i, a): (&[u8], u8) = be_u8::<_, (_, ErrorKind)>(input).unwrap();
    Ok((i, a))
}

pub fn parse_message_type(input: &[u8]) -> IResult<&[u8], u8> {
    let (i, a): (&[u8], u8) = be_u8::<_, (_, ErrorKind)>(input).unwrap();
    Ok((i, a))
}

pub fn parse_sequence_number(input: &[u8]) -> IResult<&[u8], u16> {
    let (i, a): (&[u8], u16) = be_u16::<_, (_, ErrorKind)>(input).unwrap();
    Ok((i, a))
}

pub fn parse_update_time(input: &[u8]) -> IResult<&[u8], u32> {
    let (i, a): (&[u8], u32) = be_u32::<_, (_, ErrorKind)>(input).unwrap();
    Ok((i, a))
}

pub fn parse_latitude(input: &[u8]) -> IResult<&[u8], f32> {
    let (i, a): (&[u8], i32) = be_i32::<_, (_, ErrorKind)>(input).unwrap();
    let b = (a as f32) * 10.000;
    Ok((i, b))
}

#[derive(Debug, PartialEq, Eq)]
pub enum MobileIDType {
    Off,
    /// Electronic Serial Number (ESN) of the LMU
    Esn,
    /// International Mobile Equipment Identifier (IMEI) or Electronic Identifier (EID) of the wireless modem
    Equipment,
    /// International Mobile Subscriber Identifier (IMSI) of the SIM card (GSM/GPRS devices only)
    Subscriber,
    /// User Defined Mobile ID
    Defined,
    /// Phone Number ofkk the mobile (if available)
    PhoneNumber,
    /// The current IP Address of the LMU
    IpAddress,
    /// CDMA Mobile Equipment ID (MEID) or International Mobile Equipment Identifier (IMEI) of the wireless modem
    Cdma,
}

// FIX: is necessary call multiple be_u8
pub fn parse_mobile_id_type(input: &[u8]) -> IResult<&[u8], MobileIDType> {
    let (i, _): (&[u8], u8) = be_u8::<_, (_, ErrorKind)>(input).unwrap();
    let (i, b): (&[u8], u8) = be_u8::<_, (_, ErrorKind)>(i).unwrap();
    match b {
        0 => Ok((i, MobileIDType::Off)),
        1 => Ok((i, MobileIDType::Esn)),
        2 => Ok((i, MobileIDType::Equipment)),
        3 => Ok((i, MobileIDType::Subscriber)),
        4 => Ok((i, MobileIDType::Defined)),
        5 => Ok((i, MobileIDType::PhoneNumber)),
        6 => Ok((i, MobileIDType::IpAddress)),
        7 => Ok((i, MobileIDType::Cdma)),
        _ => panic!("not found"),
    }
}

/// Event Report messages
///
/// Initiated by the LMU and are generated by the LMU’s Programmable Event
/// Generator (PEG). They can be either Acknowledged or Unacknowledged Requests.
/// The Server should respond to an Acknowledged Event Report Request with an
/// Acknowledge Message. Event reports have the following structure:
#[derive(Debug)]
pub struct EventReport<'a> {
    /// The time tag of the message in seconds.
    pub update_time: u32,
    /// The last known time of fix from the GPS satellites.
    pub time_to_fix: u32,
    /// The latitude reading of the GPS receiver, measured in degrees with a
    /// 1x10^-7 degree lsb, signed 2’s complement.
    pub latitude: f32,
    /// The longitude reading of the GPS receiver, measured in degrees with a
    /// 1x10^-7 degree lsb, signed 2’s complement.
    pub longitude: f32,
    /// The altitude reading of the GPS receiver measured in centimeters above
    /// the WGS-84 Datum, signed 2’s complement.
    pub altitude: f32,
    /// The speed as reported by the GPS receiver, measured in centimeters per
    /// second.
    pub speed: f32,
    /// The heading value reported in degrees from true North.
    pub heading: u16,
    /// The number of satellites used in the GPS solution.
    pub satellites: u8,
    /// The current fix status of the GPS receiver bitmapped as follows
    pub fix_status: u8,
    /// The identifier of the Carrier/Operator the wireless modem is currently
    /// using. For GSM, HSPA, and LTE networks, this is the MNC (mobile network
    /// code). For CDMA networks this is the SID (system identification number).
    pub carrier: u16,
    // pub carrier_ms: u16,
    /// The received signal strength of the wireless modem in dBm. This value is
    /// signed in a 2’s complement format.
    pub rssi: u8,
    /// The current state of the wireless modem bit mapped as follows
    ///
    /// Bit 0 – Available
    ///
    /// Bit 1 – Network Service
    ///
    /// Bit 2 – Data Service
    ///
    /// Bit 3 – Connected (PPP Session Up)
    ///
    /// Bit 4 – Voice Call is Active
    ///
    /// Bit 5 – Roaming
    ///
    /// Bits 6-7 – Network Technology
    ///
    /// 00 = 2G Network (CDMA or GSM)
    ///
    /// 01 = 3G Network (UMTS)
    ///
    /// 10 = 4G Network (LTE)
    ///
    /// 11 = Reserved
    pub comm_state: u8,
    /// The GPS Horizontal Dilution of Precision - it is a unit-less value
    /// reported with a 0.1 lsb.
    pub hdop: u8,
    /// The current state of the inputs, bit mapped as follows:
    ///
    /// Bit 0 – Ignition
    ///
    /// Bit 1 – Input 1
    ///
    /// Bit 2 – Input 2
    ///
    /// Bit 3 – Input 3
    ///
    /// Bit 4 – Input 4
    ///
    /// Bit 5 – Input 5
    ///
    /// Bit 6 – Input 6
    ///
    /// Bit 7 – Input 7
    pub inputs: u8,
    /// Status of key modules within the unit:
    ///
    /// Bit 0 – LMU32: HTTP OTA Update Status (0=OK, 1=Error), LMU8: Unused
    ///
    /// Bit 1 – GPS Antenna Status (0=OK, 1=Error)
    ///
    /// Bit 2 – GPS Receiver Self-Test (0=OK, 1=Error) (LMU32 only)
    ///
    /// Bit 3 – GPS Receiver Tracking (0=Yes, 1=No)
    ///
    /// Bit 4 – Reserved, Currently Unused
    ///
    /// Bit 5 – Reserved, Currently Unused
    ///
    /// Bit 6 – Reserved, Currently Unused
    ///
    /// Bit 7 – Unused
    pub unit_status: u8,
    /// The index number of the event that generated the report; values should
    /// range from 0-249. 255 represents a Real Time PEG Action request.
    pub event_index: u8,
    /// The event code assigned to the report as specified by the event’s Action
    /// Parameter
    pub event_code: u8,
    /// The number of 4-byte values in the AccumList and the Accumulator
    /// Reporting Format Type (upper 2 bits).
    pub accums: u8,
    /// This bit-mapped byte is used to indicate the presence, when
    /// corresponding bit is set, of specific data types appended to the end of
    /// the Event Report following the list of accumulators. Each data type
    /// starts with a single length byte followed by the data. If multiple data
    /// types are present, they shall appear in order of the bits set in the
    /// ‘Append’ byte, starting with bit 0.
    ///
    /// Bit 0 – Cell Info (see ‘Appended Data’ section below).
    ///
    /// Bit 1 thru 7 – reserved, set to zero (0).
    pub append: u8,
    /// A list of ‘n’ 4-byte fields where ‘n’ is defined in the Accums field.
    /// The format for this list is dependent upon the Accumulator Reporting
    /// Format Type also defined in the Accums field. Refer to Appendix G,
    /// ‘Accumulator Reporting Formats’ for details.
    pub accum_list: &'a [u8],
}

#[derive(Debug)]
pub struct OptionsStatus {
    /// MobileID is set
    is_mobile_id: bool,
    /// MobileIdType is set
    is_mobile_id_type: bool,
    /// Authentication World is set
    is_authentication_world: bool,
    /// Routing is set
    is_routing: bool,
    /// Forwarding is set
    is_forwarding: bool,
    /// Response redirections is set
    is_response_redirection: bool,
    /// Options extension is set
    is_options_extension: bool,
    /// Options headers exist
    is_always_set: bool,
}

impl OptionsStatus {
    pub fn is_mobile_id(&self) -> bool {
        self.is_mobile_id
    }

    pub fn is_mobile_id_type(&self) -> bool {
        self.is_mobile_id_type
    }

    pub fn is_authentication_world(&self) -> bool {
        self.is_authentication_world
    }

    pub fn is_routing(&self) -> bool {
        self.is_routing
    }

    pub fn is_forwarding(&self) -> bool {
        self.is_forwarding
    }

    pub fn is_response_redirection(&self) -> bool {
        self.is_response_redirection
    }

    pub fn is_options_extension(&self) -> bool {
        self.is_options_extension
    }

    pub fn is_always_set(&self) -> bool {
        self.is_always_set
    }
}

pub fn parse_options_status(input: &[u8]) -> IResult<&[u8], OptionsStatus> {
    #[allow(clippy::type_complexity)]
    let (i, b): (&[u8], (u8, u8, u8, u8, u8, u8, u8, u8)) =
        bits::<_, _, Error<(&[u8], usize)>, _, _>(tuple((
            streaming::take(1u8),
            streaming::take(1u8),
            streaming::take(1u8),
            streaming::take(1u8),
            streaming::take(1u8),
            streaming::take(1u8),
            streaming::take(1u8),
            streaming::take(1u8),
        )))(input)?;
    Ok((
        i,
        OptionsStatus {
            is_mobile_id: b.7 == 1,
            is_mobile_id_type: b.6 == 1,
            is_authentication_world: b.5 == 1,
            is_routing: b.4 == 1,
            is_forwarding: b.3 == 1,
            is_response_redirection: b.2 == 1,
            is_options_extension: b.1 == 1,
            is_always_set: b.0 == 1,
        },
    ))
}

#[cfg(test)]
mod tests {
    use super::{parse_mobile_id_type, parse_options_status};
    use crate::{
        parse_latitude, parse_message_type, parse_sequence_number,
        parse_service_type, parse_update_time, MobileID, MobileIDType,
        OptionsStatus,
    };

    #[test]
    fn test_parse_options_status() {
        let data: [u8; 117] = [
            0x83, 0x05, 0x46, 0x34, 0x66, 0x32, 0x35, 0x01, 0x01, 0x01, 0x02,
            0x3a, 0x86, 0x5f, 0xf1, 0x3a, 0x54, 0x5f, 0xf1, 0x3a, 0x57, 0xf1,
            0xe2, 0x85, 0x78, 0xe4, 0x22, 0xd6, 0x40, 0x00, 0x01, 0x36, 0xf8,
            0x00, 0x00, 0x00, 0x0b, 0x00, 0x00, 0x06, 0x20, 0x00, 0x00, 0xff,
            0x8d, 0x02, 0x1e, 0x1e, 0x00, 0x7b, 0x21, 0x10, 0x00, 0x00, 0x00,
            0x31, 0xe0, 0x00, 0x00, 0x10, 0x1a, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x22, 0x2a, 0x32, 0x00, 0x00, 0x03, 0xf1, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x01, 0xc8, 0x2d, 0x3f, 0x01, 0xc8, 0x2d,
            0x3f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x01, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        ];

        let (i, b): (&[u8], OptionsStatus) =
            parse_options_status(&data).unwrap();

        assert_eq!(b.is_mobile_id(), true);
        assert_eq!(b.is_mobile_id_type(), true);
        assert_eq!(b.is_authentication_world(), false);
        assert_eq!(b.is_routing(), false);
        assert_eq!(b.is_forwarding(), false);
        assert_eq!(b.is_response_redirection(), false);
        assert_eq!(b.is_options_extension(), false);
        assert_eq!(b.is_always_set(), true);

        if b.is_mobile_id() {
            let (i, mobileid): (&[u8], MobileID) = MobileID::parse(i).unwrap();
            assert_eq!(mobileid.len(), 5);
            assert_eq!(mobileid.to_string(), String::from("4634663235"));

            if b.is_mobile_id_type() {
                let (i, mobileidtp): (&[u8], MobileIDType) =
                    parse_mobile_id_type(i).unwrap();
                assert_eq!(mobileidtp, MobileIDType::Esn);

                // message header
                let (i, service_type) = parse_service_type(i).unwrap();
                assert_eq!(service_type, 1);
                let (i, message_type) = parse_message_type(i).unwrap();
                assert_eq!(message_type, 2);
                let (i, sequence_number) = parse_sequence_number(i).unwrap();
                assert_eq!(sequence_number, 14982);

                // event report == message type == 2
                let (i, update_time) = parse_update_time(i).unwrap();
                assert_eq!(update_time, 1609644628);
                let (i, time_of_fix) = parse_update_time(i).unwrap();
                assert_eq!(time_of_fix, 1609644631);
                let (i, latitude) = parse_latitude(i).unwrap();
                assert_eq!(latitude, -2368129300.0);
                let (i, longitude) = parse_latitude(i).unwrap();
                assert_eq!(longitude, -4674790000.0);
                let (i, altitude) = parse_update_time(i).unwrap();
                assert_eq!(altitude, 79608);
                let (i, speed) = parse_update_time(i).unwrap();
                assert_eq!(speed, 11);
                let (i, heading) = parse_sequence_number(i).unwrap();
                assert_eq!(heading, 0);
                let (i, satellites) = parse_message_type(i).unwrap();
                assert_eq!(satellites, 6);
                let (i, fix_status) = parse_message_type(i).unwrap();
                assert_eq!(fix_status, 32);
                let (i, carrier) = parse_sequence_number(i).unwrap();
                assert_eq!(carrier, 0);
                // FIX: is int16? signed singal rssi
                let (i, rssi) = parse_sequence_number(i).unwrap();
                assert_eq!(rssi, 65421);
                // FIX: get bit map enum
                let (i, comm_state) = parse_message_type(i).unwrap();
                assert_eq!(comm_state, 2);
                // println!("comm state: {:#010b}", comm_state);
                // https://en.wikipedia.org/wiki/Dilution_of_precision_(navigation)
                let (i, hdop) = parse_message_type(i).unwrap();
                assert_eq!(hdop, 30);
                // FIX: get bit map enum
                let (i, inputs) = parse_message_type(i).unwrap();
                assert_eq!(inputs, 30);
                // println!("inputs : {:#010b}", inputs);
                let (i, unit_status) = parse_message_type(i).unwrap();
                assert_eq!(unit_status, 0);
                let (i, event_index) = parse_message_type(i).unwrap();
                assert_eq!(event_index, 123);
                let (i, event_code) = parse_message_type(i).unwrap();
                assert_eq!(event_code, 33);
                let (i, accums) = parse_message_type(i).unwrap();
                assert_eq!(accums, 16);
                let (i, append) = parse_message_type(i).unwrap();
                assert_eq!(append, 0);
                let (_, accum_list) = parse_update_time(i).unwrap();
                assert_eq!(accum_list, 12768);
            }
        }
    }
}
